Repository cse110-sp24-group27/warmup-exercise, pull requests merged in 2024-04, with the labels that each got.

#6 added style
  taskList/styles.css
Labels: enhancement

#7 Finished basic sentiment widget
  .vscode/settings.json
  sentiment/index.html
  sentiment/mystyle.css
  sentiment/script.js
Labels: group2

#13 align stars
  sentiment/mystyle.css
Labels: group2

#15 Added document.md and code comments
  sentiment/assets/brainstorm.png
  sentiment/assets/img1.png
  sentiment/assets/img2.png
  sentiment/assets/img3.png
  sentiment/assets/img4.png
  sentiment/documentation.md
  sentiment/index.html
  sentiment/mystyle.css
  sentiment/script.js
Labels: group2

#17 centered button and changed cell size
  taskList/Screenshot 2024-04-23 at 17.39.04.png
  taskList/index.html
  taskList/styles.css
  taskList/task_list.md
Labels: enhancement, group1
